# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelhistory',
            old_name='model', new_name='model_name')
    ]
