# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20170314_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
